apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkxOTAzLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJiR2xyYVhSb1lUcEJiVzFoUURFNU1ETT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson